# Generated by Django 5.0.4 on 2024-05-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wally', '0011_commande_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prenom',
        ),
    ]
